CREATE SCHEMA IF NOT EXISTS Biblioteca;
#DA RIGUARDARE TUTTI I CONSTRAINT(VINCOLI)
USE Biblioteca;

CREATE TABLE EDITORE(
    CODICE      INT             NOT NULL,
    TELEFONO    VARCHAR(12),
    NOME_ED     VARCHAR(20)     NOT NULL,
    VIA         VARCHAR(30),
    CIVICO      VARCHAR(4),
    CAP         CHAR(5),
    CITTA       VARCHAR(10),
    PRIMARY KEY(CODICE),
    UNIQUE(NOME_ED)
);


CREATE TABLE LIBRO(
    ISBN        CHAR(11)        NOT NULL,
    TITOLO      VARCHAR(50)     NOT NULL,   #come attributo unique
    ANNO_PUBBL  DATE,
    COD_ED      INT             NOT NULL	DEFAULT '0',
    
    PRIMARY KEY(ISBN),
    UNIQUE(TITOLO),
    FOREIGN KEY(COD_ED) REFERENCES EDITORE(CODICE)
        ON DELETE CASCADE ON UPDATE CASCADE  #da mettere ON DELETE SET DEFAULT
											 #MA CON INNODB NON FUNZIONA QUESTA CLAUSOLA
);
#per la creazione di autore viene messo come chiave primaria
#un id unico dato all inserimento nel database(cosi da rispettare anche 
#la seconda formanormale e non avere problemi di dipendenze funzionali

CREATE TABLE AUTORE(
    ID_AUT          INT         NOT NULL,
    NOME_A          VARCHAR(15) NOT NULL,        
    COGNOME_A       VARCHAR(15) NOT NULL, 
    DATANASCITA     DATE,
    LUOGO_NASCITA   VARCHAR(20),        #presumendo 
    #che per luogo si intenda solo la citta
    
    PRIMARY KEY(ID_AUT)
);


#poiche nella carta dello studente la matricola è del
#tipo 0000144195
CREATE TABLE STUDENTE(
    MATRICOLA   CHAR(10)        NOT NULL,
    NOME        VARCHAR(15)     NOT NULL,
    COGNOME     VARCHAR(15)     NOT NULL,
    NUMERO_TELEFONO   VARCHAR(12),
    VIA         VARCHAR(30),
    CIVICO      VARCHAR(4),
    CAP         CHAR(5),
    CITTA       VARCHAR(10),
    PRIMARY KEY(MATRICOLA)
);

CREATE TABLE LINGUA(
    NOME_LINGUA     VARCHAR(15)     NOT NULL,
    PRIMARY KEY(NOME_LINGUA)
);

CREATE TABLE DIPARTIMENTO(
    NOME_DIP    VARCHAR(50)        NOT NULL,  
    VIA         VARCHAR(30),
    CIVICO      VARCHAR(4),
    CAP         CHAR(5),
    CITTA       VARCHAR(10),
    PRIMARY KEY (NOME_DIP)
);

#AMMETTENDO CHE SE UN LIBRO VIENE TOLTO DAL 
#DATABASE è PERCHE SONO STATE ROTTE TUTTE LE SUE COPIE
#E NON è PIU DISPONIBILE

#SET DEFAULT PERCHE SE UN DIPARTIMENTO NON ESISTE PIU
#LE SUE COPIE RIMANGONO IN UN DIPARTIMENTO "FITTIZIO"
#COSICCHè NEL MOMENTO DEL LORO TRASFERIMENTO VENGA
#POI AGGIORNATO CON IL DIPARTIMENTO IN CUI VERRANNO MESSI


CREATE TABLE COPIA(
    NUMERO_COPIA      INT       NOT NULL,
    ISBN        CHAR(11)        NOT NULL,
    NOME_DIP    VARCHAR(50)     NOT NULL      DEFAULT 'IN TRASFERIMENTO',
    PRIMARY KEY(NUMERO_COPIA, ISBN),
    FOREIGN KEY(ISBN) REFERENCES LIBRO(ISBN)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(NOME_DIP) REFERENCES DIPARTIMENTO(NOME_DIP)
        ON UPDATE CASCADE ON DELETE CASCADE	#NON SI PUO SETTARE ON DELETE SET NULL PERCHè è
												#CHIAVE PRIMARIA NELLO SCHEMA SOPRA ED è NOT NULL
);

#SERVIREBBE UN MECCANISMO PER EVITAARE CHE UNA MATRICOLA
#VENGA ELIMINATA SE C'è ANCORA UN PRESTITO CON QUELLA MATRICOLA

#ON DELETE CASCADE POICHè NOL MMOMENTO IN CUI SMETTO DI ESSERE UNO 
#STUDENTE L'UNIVERSITà NON HA PIU BISOGNO DI MANTENERE QUEL DATO
CREATE TABLE PRESTITO(
    ISBN            CHAR(11)        NOT NULL,
    NUMERO_COPIA    INT             NOT NULL,
    MATRICOLA       CHAR(10)        NOT NULL,
    DATA_USCITA     DATE            NOT NULL,
    PRIMARY KEY(MATRICOLA, ISBN,NUMERO_COPIA),
    FOREIGN KEY(ISBN) REFERENCES LIBRO(ISBN)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(MATRICOLA) REFERENCES STUDENTE(MATRICOLA)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(NUMERO_COPIA) REFERENCES COPIA(NUMERO_COPIA)
        ON UPDATE CASCADE ON DELETE CASCADE
);

#NON SI DOVREBBE PERò POTER CANCELLARE LE LINGUE MA NEL MECCANISMO
#IN CUI LO SI FACCIA VERREBBE ELIMINATA ANCHE DA QUESTA RELAZIONE

CREATE TABLE E_SCRITTO( 
    ISBN            CHAR(11)        NOT NULL,
    NOME_LINGUA     CHAR(15)        NOT NULL,
    PRIMARY KEY(ISBN,NOME_LINGUA),
    FOREIGN KEY(ISBN) REFERENCES LIBRO(ISBN)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(NOME_LINGUA) REFERENCES LINGUA(NOME_LINGUA) 
        ON DELETE CASCADE ON UPDATE CASCADE
);

#AMMAETTENDO CHE NON CI SIANO èIU LIBRI NEL DATABASE SCRITTI
#DA QUELL'AUTORE E L'AUTORE VENGA ELIMINATO ALLORA SI ELIMINERA
#ANCHE DA QUI 

CREATE TABLE SCRIVE(
    ISBN            CHAR(11)        NOT NULL,
    ID_AUT          INT             NOT NULL,
    PRIMARY KEY(ISBN,ID_AUT),
    FOREIGN KEY(ISBN) REFERENCES LIBRO(ISBN)
        ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY(ID_AUT) REFERENCES AUTORE(ID_AUT)
        ON DELETE CASCADE ON UPDATE CASCADE
);
