/*
-- Query: SELECT NOME_LINGUA
FROM `Biblioteca`.`LINGUA`
LIMIT 0, 1000

-- Date: 2020-05-31 10:42
*/
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Albanian');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Arabic');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Aymara');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Belarusian');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Bengali');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Catalan');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Chinese');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Czech');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Danish');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Dari');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Dhivehi');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Dutch');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Dzongkha');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('English');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Estonian');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Finnish');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('French');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Georgian');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('German');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Guaraní');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Gujarati');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Haitian Creole');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Hebrew');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Hindi');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Hiri Motu');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Hungarian');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Icelandic');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Indonesian');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Irish Gaelic');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Italian');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Japanese');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Kashmiri');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Kazakh');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Khmer');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Korean');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Lao');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Northern Sotho');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Norwegian');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Polish');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Portuguese');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Punjabi');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Quechua');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Romanian');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Spanish');
INSERT INTO LINGUA (`NOME_LINGUA`) VALUES ('Swedish');
